#!/usr/bin/env python3
"""
Fetch live GitHub stats for educational resources.

Usage:
    uv run scripts/update_stars.py           # Print stats to stdout
    uv run scripts/update_stars.py --update  # Update resources/courses.md

Requires: httpx (uv will auto-install from inline metadata)
"""
# /// script
# requires-python = ">=3.11"
# dependencies = ["httpx"]
# ///

import argparse
import json
import re
import sys
from pathlib import Path

import httpx

# Repositories to track (owner/repo)
REPOS = [
    # Karpathy
    "karpathy/nanoGPT",
    "karpathy/llm.c",
    "karpathy/minGPT",
    "karpathy/nn-zero-to-hero",
    "karpathy/llama2.c",
    "karpathy/micrograd",
    "karpathy/char-rnn",
    "karpathy/minbpe",
    "karpathy/makemore",
    "karpathy/build-nanogpt",
    "karpathy/autoresearch",
    "karpathy/nanochat",
    "karpathy/LLM101n",
    "karpathy/llm-council",
    # Raschka
    "rasbt/LLMs-from-scratch",
    "rasbt/deeplearning-models",
    "rasbt/python-machine-learning-book",
    "rasbt/mlxtend",
    "rasbt/reasoning-from-scratch",
    "rasbt/machine-learning-book",
    "rasbt/LLM-workshop-2024",
    # Stanford CS336
    "stanford-cs336/lectures",
    "stanford-cs336/assignment1-basics",
    "stanford-cs336/assignment2-systems",
    "stanford-cs336/assignment3-scaling",
    "stanford-cs336/assignment4-data",
    "stanford-cs336/assignment5-alignment",
    # Other
    "no-magic-ai/no-magic",
    "stanford-crfm/helm",
]

# Users to track followers
USERS = ["karpathy", "rasbt", "percyliang"]


def fetch_repo_stats(client: httpx.Client, repo: str) -> dict | None:
    """Fetch stars and description for a repository."""
    url = f"https://api.github.com/repos/{repo}"
    try:
        resp = client.get(url)
        if resp.status_code == 200:
            data = resp.json()
            return {
                "repo": repo,
                "stars": data["stargazers_count"],
                "description": data["description"],
                "url": data["html_url"],
            }
        elif resp.status_code == 403:
            print(
                f"Rate limited. Try again later or use GITHUB_TOKEN.", file=sys.stderr
            )
            return None
        else:
            print(f"Failed to fetch {repo}: {resp.status_code}", file=sys.stderr)
            return None
    except Exception as e:
        print(f"Error fetching {repo}: {e}", file=sys.stderr)
        return None


def fetch_user_stats(client: httpx.Client, user: str) -> dict | None:
    """Fetch follower count for a user."""
    url = f"https://api.github.com/users/{user}"
    try:
        resp = client.get(url)
        if resp.status_code == 200:
            data = resp.json()
            return {
                "user": user,
                "followers": data["followers"],
                "public_repos": data["public_repos"],
                "url": data["html_url"],
            }
        else:
            print(f"Failed to fetch user {user}: {resp.status_code}", file=sys.stderr)
            return None
    except Exception as e:
        print(f"Error fetching user {user}: {e}", file=sys.stderr)
        return None


def format_number(n: int) -> str:
    """Format number with k suffix for thousands."""
    if n >= 1000:
        return f"{n / 1000:.1f}k".replace(".0k", "k")
    return str(n)


def print_stats(repos: list[dict], users: list[dict]) -> None:
    """Print stats to stdout in a readable format."""
    print("\n## GitHub Repository Stars\n")
    print("| Repository | Stars | Description |")
    print("|------------|-------|-------------|")
    for r in sorted(repos, key=lambda x: x["stars"], reverse=True):
        desc = (r["description"] or "")[:50]
        if len(r["description"] or "") > 50:
            desc += "..."
        print(f"| [{r['repo']}]({r['url']}) | {format_number(r['stars'])} | {desc} |")

    print("\n## GitHub User Followers\n")
    print("| User | Followers | Public Repos |")
    print("|------|-----------|--------------|")
    for u in sorted(users, key=lambda x: x["followers"], reverse=True):
        print(
            f"| [@{u['user']}]({u['url']}) | {format_number(u['followers'])} | {u['public_repos']} |"
        )


def generate_live_stats_section(repos: list[dict], users: list[dict]) -> str:
    """Generate markdown section with live stats."""
    lines = [
        "## Live GitHub Stats",
        "",
        "*Auto-generated by `scripts/update_stars.py`*",
        "",
        "### Repository Stars",
        "",
        "| Repository | Stars |",
        "|------------|-------|",
    ]

    for r in sorted(repos, key=lambda x: x["stars"], reverse=True):
        lines.append(f"| [{r['repo']}]({r['url']}) | {format_number(r['stars'])} |")

    lines.extend(
        [
            "",
            "### User Followers",
            "",
            "| User | Followers |",
            "|------|-----------|",
        ]
    )

    for u in sorted(users, key=lambda x: x["followers"], reverse=True):
        lines.append(
            f"| [@{u['user']}]({u['url']}) | {format_number(u['followers'])} |"
        )

    return "\n".join(lines)


def update_courses_md(stats_section: str) -> None:
    """Update or append live stats section in courses.md."""
    courses_path = Path(__file__).parent.parent / "resources" / "courses.md"

    if not courses_path.exists():
        print(f"File not found: {courses_path}", file=sys.stderr)
        sys.exit(1)

    content = courses_path.read_text()

    # Pattern to find existing live stats section
    pattern = r"## Live GitHub Stats\n.*?(?=\n## |\Z)"

    if re.search(pattern, content, re.DOTALL):
        # Replace existing section
        new_content = re.sub(pattern, stats_section + "\n", content, flags=re.DOTALL)
    else:
        # Append at end
        new_content = content.rstrip() + "\n\n---\n\n" + stats_section + "\n"

    courses_path.write_text(new_content)
    print(f"Updated {courses_path}")


def main():
    parser = argparse.ArgumentParser(description="Fetch live GitHub stats")
    parser.add_argument(
        "--update", action="store_true", help="Update resources/courses.md"
    )
    parser.add_argument("--json", action="store_true", help="Output as JSON")
    args = parser.parse_args()

    # Use token if available (higher rate limits)
    import os

    token = os.environ.get("GITHUB_TOKEN")
    headers = {"Accept": "application/vnd.github.v3+json"}
    if token:
        headers["Authorization"] = f"token {token}"

    with httpx.Client(headers=headers, timeout=30) as client:
        # Fetch repo stats
        repos = []
        for repo in REPOS:
            if stats := fetch_repo_stats(client, repo):
                repos.append(stats)

        # Fetch user stats
        users = []
        for user in USERS:
            if stats := fetch_user_stats(client, user):
                users.append(stats)

    if not repos:
        print("No data fetched. Check rate limits or network.", file=sys.stderr)
        sys.exit(1)

    if args.json:
        print(json.dumps({"repos": repos, "users": users}, indent=2))
    elif args.update:
        stats_section = generate_live_stats_section(repos, users)
        update_courses_md(stats_section)
    else:
        print_stats(repos, users)


if __name__ == "__main__":
    main()
